### Site metadata ###

title: constantpinger 
description: "A Network Engineer's Attempt at Coding"
show_downloads: true
email:
twitter_username: constantpinger
github_username: constantpinger
rss: RSS

### Build settings ###

url: https://constantpinger.github.io
baseurl: /
remote_theme: carlosperate/jekyll-theme-rtd
#theme: jekyll-theme-cayman

permalink: pretty

exclude:
  - docs/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict
