title: constantpinger
description: Github Pages Test Site
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Ian Nightingale
repo_url: "https://github.com/constantpinger"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
titles_only: True
